// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "M\u016Fj profil",
  description: "Vr\xE1t\xED profil p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele: jm\xE9no, body, stav platby a role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161eno" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("display_name, total_points, current_level, has_paid, created_at").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const result = {
      email: ctx.getUserEmail() ?? null,
      profile: profile ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_progress_default = defineTool2({
  name: "get_my_progress",
  title: "M\u016Fj pokrok",
  description: "Vr\xE1t\xED pokrok p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele v jednotliv\xFDch levelech a skupin\xE1ch (dokon\u010Deno, sk\xF3re).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161eno" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [levelRes, groupRes] = await Promise.all([
      supabase.from("user_progress").select("level_id, completed, test_score, completed_at").eq("user_id", userId),
      supabase.from("user_group_progress").select("group_id, passed, test_score, completed_at").eq("user_id", userId)
    ]);
    const error = levelRes.error ?? groupRes.error;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const result = {
      levels: levelRes.data ?? [],
      groups: groupRes.data ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-levels.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_levels_default = defineTool3({
  name: "list_levels",
  title: "Seznam level\u016F",
  description: "Vyp\xED\u0161e dostupn\xE9 levely (voliteln\u011B filtrovan\xE9 podle kategorie) v\u010Detn\u011B skupiny a po\u010Dtu ot\xE1zek.",
  inputSchema: {
    category: z.string().optional().describe("Voliteln\xFD filtr kategorie, nap\u0159. 'products' nebo 'backoffice'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161eno" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("levels").select("id, title, description, category, order_index, passing_score, group_id").order("order_index", { ascending: true });
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const levels = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(levels) }],
      structuredContent: { levels }
    };
  }
});

// src/lib/mcp/tools/list-my-certificates.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_certificates_default = defineTool4({
  name: "list_my_certificates",
  title: "Moje certifik\xE1ty",
  description: "Vyp\xED\u0161e certifik\xE1ty vydan\xE9 p\u0159ihl\xE1\u0161en\xE9mu u\u017Eivateli v\u010Detn\u011B skupiny a pr\u016Fm\u011Brn\xE9ho sk\xF3re.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161eno" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("issued_diplomas").select("id, group_id, average_score, issued_at").eq("user_id", ctx.getUserId()).order("issued_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const certificates = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(certificates) }],
      structuredContent: { certificates }
    };
  }
});

// src/lib/mcp/tools/list-my-review-items.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_review_items_default = defineTool5({
  name: "list_my_review_items",
  title: "Moje opakov\xE1n\xED",
  description: "Vyp\xED\u0161e ot\xE1zky za\u0159azen\xE9 do opakov\xE1n\xED pro p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele (bez spr\xE1vn\xFDch odpov\u011Bd\xED).",
  inputSchema: {
    confidence: z2.string().optional().describe("Voliteln\xFD filtr \xFArovn\u011B jistoty, nap\u0159. 'low'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ confidence }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161eno" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("review_items").select("id, question_id, confidence, source, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (confidence) query = query.eq("confidence", confidence);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const items = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(items) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ftxocctxltyqdvrgmzgw";
var mcp_default = defineMcp({
  name: "zgrp-academy",
  title: "ZGRP ACADEMY",
  version: "0.1.0",
  instructions: "N\xE1stroje vzd\u011Bl\xE1vac\xED platformy ZGRP Academy. Umo\u017E\u0148uj\xED \u010D\xEDst profil p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele, jeho pokrok v levelech a skupin\xE1ch, polo\u017Eky k opakov\xE1n\xED a vydan\xE9 certifik\xE1ty. V\u0161e je omezeno na \xFA\u010Det p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    list_levels_default,
    get_my_progress_default,
    list_my_review_items_default,
    list_my_certificates_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
